package de.training.playground.integration.database;

import de.training.playground.entity.Todo;
import de.training.playground.repository.TodoRepository;
import io.qameta.allure.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Datenbank-Tests mit H2 In-Memory Database.
 *
 * <p>H2 ist eine eingebettete Java-Datenbank, die im Speicher laeuft
 * und ideal fuer schnelle Tests ist.
 *
 * <p>Demonstriert:
 * <ul>
 *   <li>Automatische ID-Generierung ({@code @GeneratedValue})</li>
 *   <li>Persistenz verschiedener Datentypen (String, LocalDate, Boolean)</li>
 *   <li>CRUD-Operationen (Create, Read, Update, Delete)</li>
 *   <li>Repository-Methoden wie {@code count()}, {@code findAll()}</li>
 * </ul>
 *
 * <p><b>Vorteile von H2:</b>
 * <ul>
 *   <li>Sehr schnell (In-Memory)</li>
 *   <li>Keine Installation noetig</li>
 *   <li>Automatisches Schema-Management</li>
 * </ul>
 *
 * <p><b>Nachteile:</b> Verhält sich nicht 100% wie PostgreSQL/MySQL
 * (siehe {@link de.training.playground.integration.testcontainers.TodoPostgresContainerTest})
 *
 * @see org.springframework.boot.test.context.SpringBootTest
 */
@Epic("Integration Tests")
@Feature("database")
@SpringBootTest
@Transactional
@DisplayName("H2 Datenbank-Tests")
class TodoH2Test {

    @Autowired
    private TodoRepository repository;

    @BeforeEach
    void setUp() {
        repository.deleteAll();
    }

    @Test
    @DisplayName("Todo mit automatisch generierter ID speichern")
    void autoGeneratedId() {
        Todo todo = new Todo();
        todo.setTitle("Test");

        Todo saved = repository.save(todo);

        assertThat(saved.getId()).isNotNull();
        assertThat(saved.getId()).isPositive();
    }

    @Test
    @DisplayName("Mehrere Todos mit aufsteigenden IDs")
    void sequentialIds() {
        Todo todo1 = repository.save(createTodo("Erstes"));
        Todo todo2 = repository.save(createTodo("Zweites"));
        Todo todo3 = repository.save(createTodo("Drittes"));

        assertThat(todo1.getId()).isLessThan(todo2.getId());
        assertThat(todo2.getId()).isLessThan(todo3.getId());
    }

    @Test
    @DisplayName("Datumsfelder werden korrekt gespeichert")
    void dateFieldsPersisted() {
        Todo todo = new Todo();
        todo.setTitle("Mit Datum");
        todo.setDueDate(LocalDate.of(2026, 6, 15));

        Todo saved = repository.save(todo);

        assertThat(saved.getDueDate()).isEqualTo(LocalDate.of(2026, 6, 15));
    }

    @Test
    @DisplayName("Boolean-Feld wird korrekt gespeichert")
    void booleanFieldPersisted() {
        Todo todo = new Todo();
        todo.setTitle("Erledigt");
        todo.markDone();

        Todo saved = repository.save(todo);

        assertThat(saved.isDone()).isTrue();
    }

    @Test
    @DisplayName("Update aendert existierenden Datensatz")
    void updateExisting() {
        Todo todo = repository.save(createTodo("Original"));
        Long id = todo.getId();

        todo.setTitle("Geaendert");
        repository.save(todo);

        Todo reloaded = repository.findById(id).orElseThrow();
        assertThat(reloaded.getTitle()).isEqualTo("Geaendert");
    }

    @Test
    @DisplayName("Delete entfernt Datensatz")
    void deleteRemoves() {
        Todo todo = repository.save(createTodo("Zum Loeschen"));
        Long id = todo.getId();

        repository.deleteById(id);

        assertThat(repository.findById(id)).isEmpty();
    }

    @Test
    @DisplayName("Count zaehlt korrekt")
    void countWorks() {
        assertThat(repository.count()).isZero();

        repository.save(createTodo("Eins"));
        repository.save(createTodo("Zwei"));
        repository.save(createTodo("Drei"));

        assertThat(repository.count()).isEqualTo(3);
    }

    @Test
    @DisplayName("FindAll gibt alle Datensaetze")
    void findAllReturnsAll() {
        repository.save(createTodo("A"));
        repository.save(createTodo("B"));
        repository.save(createTodo("C"));

        List<Todo> all = repository.findAll();

        assertThat(all).hasSize(3);
        assertThat(all).extracting(Todo::getTitle)
            .containsExactlyInAnyOrder("A", "B", "C");
    }

    private Todo createTodo(String title) {
        Todo todo = new Todo();
        todo.setTitle(title);
        return todo;
    }
}
